const pessoas = [
  {
    idade: 29,
    corDosOlhos: "brown",
    nome: "Pacheco Finley",
    genero: "male",
    empresa: "XPLOR",
    email: "pachecofinley@xplor.com",
    tel: "+1 (977) 467-3911",
    endereco: "269 Hamilton Avenue, Sedley, District Of Columbia, 3676",
  },
  {
    idade: 22,
    corDosOlhos: "blue",
    nome: "Pennington Vincent",
    genero: "male",
    empresa: "ISOTERNIA",
    email: "penningtonvincent@isoternia.com",
    tel: "+1 (812) 461-2901",
    endereco: "757 Adams Street, Summertown, Washington, 1305",
  },
  {
    idade: 30,
    corDosOlhos: "blue",
    nome: "Hoffman Nichols",
    genero: "male",
    empresa: "ILLUMITY",
    email: "hoffmannichols@illumity.com",
    tel: "+1 (962) 418-3150",
    endereco: "171 Ruby Street, Yettem, Wisconsin, 4323",
  },
  {
    idade: 26,
    corDosOlhos: "green",
    nome: "Neal William",
    genero: "male",
    empresa: "ZOMBOID",
    email: "nealwilliam@zomboid.com",
    tel: "+1 (818) 578-2115",
    endereco: "423 Bartlett Street, Elfrida, Wyoming, 1404",
  },
  {
    idade: 20,
    corDosOlhos: "blue",
    nome: "Vilma Guy",
    genero: "female",
    empresa: "ZILLIDIUM",
    email: "vilmaguy@zillidium.com",
    tel: "+1 (927) 479-3106",
    endereco:
      "272 Kosciusko Street, Cashtown, Federated States Of Micronesia, 2729",
  },
  {
    idade: 24,
    corDosOlhos: "blue",
    nome: "Dudley Gordon",
    genero: "male",
    empresa: "MANGLO",
    email: "dudleygordon@manglo.com",
    tel: "+1 (983) 589-2119",
    endereco: "793 Vernon Avenue, Aurora, Marshall Islands, 5608",
  },
  {
    idade: 39,
    corDosOlhos: "green",
    nome: "Ingram Donovan",
    genero: "male",
    empresa: "IRACK",
    email: "ingramdonovan@irack.com",
    tel: "+1 (997) 581-2514",
    endereco: "926 Ovington Court, Westboro, Louisiana, 5337",
  },
  {
    idade: 34,
    corDosOlhos: "green",
    nome: "Amanda Gomez",
    genero: "female",
    empresa: "DAYCORE",
    email: "amandagomez@daycore.com",
    tel: "+1 (876) 524-3892",
    endereco: "581 Colonial Court, Shrewsbury, Idaho, 6732",
  },
  {
    idade: 39,
    corDosOlhos: "blue",
    nome: "Matthews Jimenez",
    genero: "male",
    empresa: "LUNCHPAD",
    email: "matthewsjimenez@lunchpad.com",
    tel: "+1 (937) 513-3095",
    endereco: "389 Noel Avenue, Emory, Northern Mariana Islands, 7831",
  },
  {
    idade: 22,
    corDosOlhos: "green",
    nome: "Houston Caldwell",
    genero: "male",
    empresa: "SUPPORTAL",
    email: "houstoncaldwell@supportal.com",
    tel: "+1 (964) 569-2813",
    endereco: "641 Lynch Street, Wescosville, Nebraska, 8594",
  },
  {
    idade: 32,
    corDosOlhos: "brown",
    nome: "Castillo Houston",
    genero: "male",
    empresa: "XELEGYL",
    email: "castillohouston@xelegyl.com",
    tel: "+1 (860) 507-3507",
    endereco: "326 Oxford Walk, Indio, Palau, 7948",
  },
  {
    idade: 24,
    corDosOlhos: "green",
    nome: "Guadalupe Hodge",
    genero: "female",
    empresa: "GEOFARM",
    email: "guadalupehodge@geofarm.com",
    tel: "+1 (960) 528-2324",
    endereco: "818 Stryker Street, Glendale, Kansas, 6040",
  },
  {
    idade: 34,
    corDosOlhos: "green",
    nome: "Jacklyn Valenzuela",
    genero: "female",
    empresa: "EXTRAWEAR",
    email: "jacklynvalenzuela@extrawear.com",
    tel: "+1 (862) 440-2750",
    endereco: "878 Coles Street, Dundee, Florida, 2978",
  },
  {
    idade: 28,
    corDosOlhos: "blue",
    nome: "Burnett Barrett",
    genero: "male",
    empresa: "HINWAY",
    email: "burnettbarrett@hinway.com",
    tel: "+1 (991) 476-3305",
    endereco: "675 Tillary Street, Springville, South Dakota, 8278",
  },
  {
    idade: 29,
    corDosOlhos: "green",
    nome: "Lenora Gay",
    genero: "female",
    empresa: "KNOWLYSIS",
    email: "lenoragay@knowlysis.com",
    tel: "+1 (870) 427-3984",
    endereco: "289 Oriental Court, Fairmount, Oregon, 1869",
  },
  {
    idade: 26,
    corDosOlhos: "blue",
    nome: "Riley Wolfe",
    genero: "male",
    empresa: "LUDAK",
    email: "rileywolfe@ludak.com",
    tel: "+1 (827) 444-3512",
    endereco: "589 Bancroft Place, Coyote, Puerto Rico, 1160",
  },
  {
    idade: 38,
    corDosOlhos: "blue",
    nome: "Crosby Macdonald",
    genero: "male",
    empresa: "NIKUDA",
    email: "crosbymacdonald@nikuda.com",
    tel: "+1 (925) 537-2149",
    endereco: "209 Madoc Avenue, Rosburg, Maine, 2596",
  },
  {
    idade: 31,
    corDosOlhos: "brown",
    nome: "Thelma Edwards",
    genero: "female",
    empresa: "KINETICA",
    email: "thelmaedwards@kinetica.com",
    tel: "+1 (820) 519-2250",
    endereco: "805 Monaco Place, Bethany, Arizona, 6615",
  },
  {
    idade: 22,
    corDosOlhos: "green",
    nome: "Shana Donaldson",
    genero: "female",
    empresa: "GUSHKOOL",
    email: "shanadonaldson@gushkool.com",
    tel: "+1 (877) 549-2946",
    endereco: "263 Doscher Street, Frank, Indiana, 9375",
  },
  {
    idade: 22,
    corDosOlhos: "blue",
    nome: "Delores White",
    genero: "female",
    empresa: "RONELON",
    email: "deloreswhite@ronelon.com",
    tel: "+1 (865) 507-2635",
    endereco: "244 McKibben Street, Onton, Pennsylvania, 5473",
  },
  {
    idade: 20,
    corDosOlhos: "blue",
    nome: "Hicks Melendez",
    genero: "male",
    empresa: "PYRAMAX",
    email: "hicksmelendez@pyramax.com",
    tel: "+1 (805) 413-3436",
    endereco: "860 Corbin Place, Sanford, Nevada, 2327",
  },
];

module.exports = { pessoas };
